apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |   # name of the file that will be mounted
    server {
        listen 80;
        location / {
            proxy_pass http://flask-app:5000;
        }
    }